services:
  intake:
    image: ghcr.io/realhinome/galadril-intake:latest
    platform: linux/amd64
    container_name: intake
    depends_on:
      - redpanda
      - minio
      - minio-init
    environment:
      - KAFKA_CONSUMER_GROUP=intake-service
      - KAFKA_TOPIC_NOTIFICATIONS=s3-bucket-notifications
      - SCHEMA_REGISTRY=http://redpanda:8081
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
      - AWS_REGION=us-east-1
    volumes:
      - ../../examples/pipeline.yaml:/pipeline.yaml
      - ../../schemas:/schemas

  vision:
    image: ghcr.io/realhinome/galadril-vision:latest
    platform: linux/amd64
    container_name: vision
    command: ["--config", "pipeline.yaml"]
    depends_on:
      - redpanda
      - minio
      - minio-init
    volumes:
      - ../../examples/pipeline.yaml:/pipeline.yaml
