services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --node-id 0
      - --overprovisioned
      - --kafka-addr 0.0.0.0:9092
      - --advertise-kafka-addr localhost:9092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
      - --set auto_create_topics_enabled=true
    ports:
      - 9092:9092
      - 8081:8081
      - 8082:8082
      - 9644:9644
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 10s
      retries: 5

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - 8090:8080
    environment:
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:9092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]