services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --node-id 0
      - --overprovisioned
      - --kafka-addr PLAINTEXT://0.0.0.0:9092,OUTSIDE://0.0.0.0:29092
      - --advertise-kafka-addr PLAINTEXT://redpanda:9092,OUTSIDE://localhost:29092
      - --pandaproxy-addr 0.0.0.0:8082
      - --advertise-pandaproxy-addr localhost:8082
    ports:
      - 8081:8081
      - 8082:8082
      - 9092:9092
      - 9092:9092
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 2s
      retries: 5

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - 8090:8080
    environment:
      KAFKA_BROKERS: redpanda:9092
      SCHEMA_REGISTRY_ENABLED: "true"
      SCHEMA_REGISTRY_URLS: http://redpanda:8081
