services:
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: redpanda
    command:
      - redpanda start
      - --smp 1
      - --memory 512M
      - --node-id 0
      - --overprovisioned
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:9092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:9092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:8082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:8082
      - --set auto_create_topics_enabled=true
    ports:
      - 9092:9092
      - 8081:8081
      - 8082:8082
      - 9644:9644
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 5s
      retries: 5

  redpanda-console:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: redpanda-console
    depends_on:
      redpanda:
        condition: service_healthy
    ports:
      - 8090:8080
    environment:
      KAFKA_BROKERS: redpanda:9092
      SCHEMA_REGISTRY_ENABLED: "true"
      SCHEMA_REGISTRY_URLS: http://redpanda:8081
