[book]
title = "Galadril Docs"
authors = ["RealHinome"]
description = "Documentation for Galadril project."
language = "en"
text-direction = "ltr"

[rust]
edition = "2024"

[preprocessor.index]
[preprocessor.links]

[output.html.search]
limit-results = 15

[output.html]
smart-punctuation = true
git-repository-url = "https://github.com/RealHinome/Galadril/tree/main/docs"
edit-url-template = "https://github.com/RealHinome/Galadril/tree/masmainter/docs/{path}"
